# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import robotics_pb2 as robotics__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robotics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoboticFleetServiceStub(object):
    """============================================================================
    ROBOTIC FLEET SERVICE DEFINITION
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterRobot = channel.unary_unary(
                '/robotics.RoboticFleetService/RegisterRobot',
                request_serializer=robotics__pb2.RobotIdentity.SerializeToString,
                response_deserializer=robotics__pb2.RobotAuthResponse.FromString,
                _registered_method=True)
        self.GetRobotHealth = channel.unary_unary(
                '/robotics.RoboticFleetService/GetRobotHealth',
                request_serializer=robotics__pb2.RobotIdentity.SerializeToString,
                response_deserializer=robotics__pb2.RobotHealth.FromString,
                _registered_method=True)
        self.SendTask = channel.unary_unary(
                '/robotics.RoboticFleetService/SendTask',
                request_serializer=robotics__pb2.RoboticTask.SerializeToString,
                response_deserializer=robotics__pb2.TaskResult.FromString,
                _registered_method=True)
        self.NavigateTo = channel.unary_unary(
                '/robotics.RoboticFleetService/NavigateTo',
                request_serializer=robotics__pb2.NavigationCommand.SerializeToString,
                response_deserializer=robotics__pb2.NavigationStatus.FromString,
                _registered_method=True)
        self.GetNavigationStatus = channel.unary_stream(
                '/robotics.RoboticFleetService/GetNavigationStatus',
                request_serializer=robotics__pb2.RobotIdentity.SerializeToString,
                response_deserializer=robotics__pb2.NavigationStatus.FromString,
                _registered_method=True)
        self.ReportSensorData = channel.unary_unary(
                '/robotics.RoboticFleetService/ReportSensorData',
                request_serializer=robotics__pb2.SensorData.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/robotics.RoboticFleetService/EmergencyStop',
                request_serializer=robotics__pb2.RobotIdentity.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/robotics.RoboticFleetService/CancelTask',
                request_serializer=robotics__pb2.RobotIdentity.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListActiveRobots = channel.unary_stream(
                '/robotics.RoboticFleetService/ListActiveRobots',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=robotics__pb2.RobotHealth.FromString,
                _registered_method=True)


class RoboticFleetServiceServicer(object):
    """============================================================================
    ROBOTIC FLEET SERVICE DEFINITION
    ============================================================================

    """

    def RegisterRobot(self, request, context):
        """*
        RegisterRobot: Initial registration and authentication of a robotic unit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotHealth(self, request, context):
        """*
        GetRobotHealth: Retrieve current health metrics for a robotic unit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTask(self, request, context):
        """*
        SendTask: Dispatch a task to a robotic unit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NavigateTo(self, request, context):
        """*
        NavigateTo: Direct a robot to a specific location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNavigationStatus(self, request, context):
        """*
        GetNavigationStatus: Get real-time navigation feedback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSensorData(self, request, context):
        """*
        ReportSensorData: Robotic unit sends sensor and health data to backend
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """*
        EmergencyStop: Immediately halt a robotic unit (safety critical)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """*
        CancelTask: Cancel an ongoing task execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveRobots(self, request, context):
        """*
        ListActiveRobots: Get list of currently active robotic units with status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoboticFleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRobot,
                    request_deserializer=robotics__pb2.RobotIdentity.FromString,
                    response_serializer=robotics__pb2.RobotAuthResponse.SerializeToString,
            ),
            'GetRobotHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotHealth,
                    request_deserializer=robotics__pb2.RobotIdentity.FromString,
                    response_serializer=robotics__pb2.RobotHealth.SerializeToString,
            ),
            'SendTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTask,
                    request_deserializer=robotics__pb2.RoboticTask.FromString,
                    response_serializer=robotics__pb2.TaskResult.SerializeToString,
            ),
            'NavigateTo': grpc.unary_unary_rpc_method_handler(
                    servicer.NavigateTo,
                    request_deserializer=robotics__pb2.NavigationCommand.FromString,
                    response_serializer=robotics__pb2.NavigationStatus.SerializeToString,
            ),
            'GetNavigationStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetNavigationStatus,
                    request_deserializer=robotics__pb2.RobotIdentity.FromString,
                    response_serializer=robotics__pb2.NavigationStatus.SerializeToString,
            ),
            'ReportSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSensorData,
                    request_deserializer=robotics__pb2.SensorData.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=robotics__pb2.RobotIdentity.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=robotics__pb2.RobotIdentity.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListActiveRobots': grpc.unary_stream_rpc_method_handler(
                    servicer.ListActiveRobots,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=robotics__pb2.RobotHealth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotics.RoboticFleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotics.RoboticFleetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoboticFleetService(object):
    """============================================================================
    ROBOTIC FLEET SERVICE DEFINITION
    ============================================================================

    """

    @staticmethod
    def RegisterRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/RegisterRobot',
            robotics__pb2.RobotIdentity.SerializeToString,
            robotics__pb2.RobotAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/GetRobotHealth',
            robotics__pb2.RobotIdentity.SerializeToString,
            robotics__pb2.RobotHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/SendTask',
            robotics__pb2.RoboticTask.SerializeToString,
            robotics__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NavigateTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/NavigateTo',
            robotics__pb2.NavigationCommand.SerializeToString,
            robotics__pb2.NavigationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNavigationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robotics.RoboticFleetService/GetNavigationStatus',
            robotics__pb2.RobotIdentity.SerializeToString,
            robotics__pb2.NavigationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/ReportSensorData',
            robotics__pb2.SensorData.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/EmergencyStop',
            robotics__pb2.RobotIdentity.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotics.RoboticFleetService/CancelTask',
            robotics__pb2.RobotIdentity.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveRobots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robotics.RoboticFleetService/ListActiveRobots',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            robotics__pb2.RobotHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
