# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sensors_pb2 as sensors__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensors_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MycelialProbeServiceStub(object):
    """Sub-Surface Mycelial Probe Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMycelialData = channel.unary_stream(
                '/aegis.sensors.MycelialProbeService/StreamMycelialData',
                request_serializer=sensors__pb2.StreamMycelialDataRequest.SerializeToString,
                response_deserializer=sensors__pb2.MycelialData.FromString,
                _registered_method=True)
        self.GetMycelialStatus = channel.unary_unary(
                '/aegis.sensors.MycelialProbeService/GetMycelialStatus',
                request_serializer=sensors__pb2.SensorLocation.SerializeToString,
                response_deserializer=sensors__pb2.MycelialStatus.FromString,
                _registered_method=True)
        self.CalibrateMycelialProbe = channel.unary_unary(
                '/aegis.sensors.MycelialProbeService/CalibrateMycelialProbe',
                request_serializer=sensors__pb2.CalibrationRequest.SerializeToString,
                response_deserializer=sensors__pb2.CalibrationResponse.FromString,
                _registered_method=True)
        self.GetMycelialProbeHealth = channel.unary_unary(
                '/aegis.sensors.MycelialProbeService/GetMycelialProbeHealth',
                request_serializer=sensors__pb2.SensorLocation.SerializeToString,
                response_deserializer=sensors__pb2.SensorHealth.FromString,
                _registered_method=True)


class MycelialProbeServiceServicer(object):
    """Sub-Surface Mycelial Probe Service
    """

    def StreamMycelialData(self, request, context):
        """Stream real-time mycelial network data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMycelialStatus(self, request, context):
        """Get current mycelial network status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateMycelialProbe(self, request, context):
        """Calibrate mycelial probe sensors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMycelialProbeHealth(self, request, context):
        """Get mycelial probe health status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MycelialProbeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMycelialData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMycelialData,
                    request_deserializer=sensors__pb2.StreamMycelialDataRequest.FromString,
                    response_serializer=sensors__pb2.MycelialData.SerializeToString,
            ),
            'GetMycelialStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMycelialStatus,
                    request_deserializer=sensors__pb2.SensorLocation.FromString,
                    response_serializer=sensors__pb2.MycelialStatus.SerializeToString,
            ),
            'CalibrateMycelialProbe': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateMycelialProbe,
                    request_deserializer=sensors__pb2.CalibrationRequest.FromString,
                    response_serializer=sensors__pb2.CalibrationResponse.SerializeToString,
            ),
            'GetMycelialProbeHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMycelialProbeHealth,
                    request_deserializer=sensors__pb2.SensorLocation.FromString,
                    response_serializer=sensors__pb2.SensorHealth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.sensors.MycelialProbeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.sensors.MycelialProbeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MycelialProbeService(object):
    """Sub-Surface Mycelial Probe Service
    """

    @staticmethod
    def StreamMycelialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aegis.sensors.MycelialProbeService/StreamMycelialData',
            sensors__pb2.StreamMycelialDataRequest.SerializeToString,
            sensors__pb2.MycelialData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMycelialStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.MycelialProbeService/GetMycelialStatus',
            sensors__pb2.SensorLocation.SerializeToString,
            sensors__pb2.MycelialStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateMycelialProbe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.MycelialProbeService/CalibrateMycelialProbe',
            sensors__pb2.CalibrationRequest.SerializeToString,
            sensors__pb2.CalibrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMycelialProbeHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.MycelialProbeService/GetMycelialProbeHealth',
            sensors__pb2.SensorLocation.SerializeToString,
            sensors__pb2.SensorHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AcousticPestMonitorServiceStub(object):
    """Acoustic Pest Monitor Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAcousticData = channel.unary_stream(
                '/aegis.sensors.AcousticPestMonitorService/StreamAcousticData',
                request_serializer=sensors__pb2.StreamAcousticDataRequest.SerializeToString,
                response_deserializer=sensors__pb2.AcousticData.FromString,
                _registered_method=True)
        self.GetPestActivityStatus = channel.unary_unary(
                '/aegis.sensors.AcousticPestMonitorService/GetPestActivityStatus',
                request_serializer=sensors__pb2.SensorLocation.SerializeToString,
                response_deserializer=sensors__pb2.PestActivityStatus.FromString,
                _registered_method=True)
        self.TriggerPestScan = channel.unary_unary(
                '/aegis.sensors.AcousticPestMonitorService/TriggerPestScan',
                request_serializer=sensors__pb2.PestScanRequest.SerializeToString,
                response_deserializer=sensors__pb2.PestScanResponse.FromString,
                _registered_method=True)
        self.CalibrateAcousticSensor = channel.unary_unary(
                '/aegis.sensors.AcousticPestMonitorService/CalibrateAcousticSensor',
                request_serializer=sensors__pb2.CalibrationRequest.SerializeToString,
                response_deserializer=sensors__pb2.CalibrationResponse.FromString,
                _registered_method=True)
        self.GetAcousticSensorHealth = channel.unary_unary(
                '/aegis.sensors.AcousticPestMonitorService/GetAcousticSensorHealth',
                request_serializer=sensors__pb2.SensorLocation.SerializeToString,
                response_deserializer=sensors__pb2.SensorHealth.FromString,
                _registered_method=True)


class AcousticPestMonitorServiceServicer(object):
    """Acoustic Pest Monitor Service
    """

    def StreamAcousticData(self, request, context):
        """Stream real-time acoustic pest detection data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPestActivityStatus(self, request, context):
        """Get current pest activity status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerPestScan(self, request, context):
        """Trigger acoustic pest scan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateAcousticSensor(self, request, context):
        """Calibrate acoustic sensors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAcousticSensorHealth(self, request, context):
        """Get acoustic sensor health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcousticPestMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAcousticData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAcousticData,
                    request_deserializer=sensors__pb2.StreamAcousticDataRequest.FromString,
                    response_serializer=sensors__pb2.AcousticData.SerializeToString,
            ),
            'GetPestActivityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPestActivityStatus,
                    request_deserializer=sensors__pb2.SensorLocation.FromString,
                    response_serializer=sensors__pb2.PestActivityStatus.SerializeToString,
            ),
            'TriggerPestScan': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerPestScan,
                    request_deserializer=sensors__pb2.PestScanRequest.FromString,
                    response_serializer=sensors__pb2.PestScanResponse.SerializeToString,
            ),
            'CalibrateAcousticSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateAcousticSensor,
                    request_deserializer=sensors__pb2.CalibrationRequest.FromString,
                    response_serializer=sensors__pb2.CalibrationResponse.SerializeToString,
            ),
            'GetAcousticSensorHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAcousticSensorHealth,
                    request_deserializer=sensors__pb2.SensorLocation.FromString,
                    response_serializer=sensors__pb2.SensorHealth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.sensors.AcousticPestMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.sensors.AcousticPestMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcousticPestMonitorService(object):
    """Acoustic Pest Monitor Service
    """

    @staticmethod
    def StreamAcousticData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aegis.sensors.AcousticPestMonitorService/StreamAcousticData',
            sensors__pb2.StreamAcousticDataRequest.SerializeToString,
            sensors__pb2.AcousticData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPestActivityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.AcousticPestMonitorService/GetPestActivityStatus',
            sensors__pb2.SensorLocation.SerializeToString,
            sensors__pb2.PestActivityStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerPestScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.AcousticPestMonitorService/TriggerPestScan',
            sensors__pb2.PestScanRequest.SerializeToString,
            sensors__pb2.PestScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateAcousticSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.AcousticPestMonitorService/CalibrateAcousticSensor',
            sensors__pb2.CalibrationRequest.SerializeToString,
            sensors__pb2.CalibrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAcousticSensorHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.AcousticPestMonitorService/GetAcousticSensorHealth',
            sensors__pb2.SensorLocation.SerializeToString,
            sensors__pb2.SensorHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SensorManagementServiceStub(object):
    """General Sensor Management Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSensor = channel.unary_unary(
                '/aegis.sensors.SensorManagementService/RegisterSensor',
                request_serializer=sensors__pb2.SensorRegistration.SerializeToString,
                response_deserializer=sensors__pb2.SensorRegistrationResponse.FromString,
                _registered_method=True)
        self.GetZoneSensors = channel.unary_unary(
                '/aegis.sensors.SensorManagementService/GetZoneSensors',
                request_serializer=sensors__pb2.GetZoneSensorsRequest.SerializeToString,
                response_deserializer=sensors__pb2.ZoneSensorsResponse.FromString,
                _registered_method=True)
        self.GetSensorNetworkHealth = channel.unary_unary(
                '/aegis.sensors.SensorManagementService/GetSensorNetworkHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sensors__pb2.SensorNetworkHealth.FromString,
                _registered_method=True)
        self.BulkCalibrateSensors = channel.unary_unary(
                '/aegis.sensors.SensorManagementService/BulkCalibrateSensors',
                request_serializer=sensors__pb2.BulkCalibrationRequest.SerializeToString,
                response_deserializer=sensors__pb2.BulkCalibrationResponse.FromString,
                _registered_method=True)
        self.EmergencyShutdown = channel.unary_unary(
                '/aegis.sensors.SensorManagementService/EmergencyShutdown',
                request_serializer=sensors__pb2.EmergencyShutdownRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SensorManagementServiceServicer(object):
    """General Sensor Management Service
    """

    def RegisterSensor(self, request, context):
        """Register a new sensor in the network
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetZoneSensors(self, request, context):
        """Get all sensors in a zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorNetworkHealth(self, request, context):
        """Get sensor network health overview
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkCalibrateSensors(self, request, context):
        """Bulk sensor calibration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyShutdown(self, request, context):
        """Emergency sensor shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSensor,
                    request_deserializer=sensors__pb2.SensorRegistration.FromString,
                    response_serializer=sensors__pb2.SensorRegistrationResponse.SerializeToString,
            ),
            'GetZoneSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetZoneSensors,
                    request_deserializer=sensors__pb2.GetZoneSensorsRequest.FromString,
                    response_serializer=sensors__pb2.ZoneSensorsResponse.SerializeToString,
            ),
            'GetSensorNetworkHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorNetworkHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sensors__pb2.SensorNetworkHealth.SerializeToString,
            ),
            'BulkCalibrateSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkCalibrateSensors,
                    request_deserializer=sensors__pb2.BulkCalibrationRequest.FromString,
                    response_serializer=sensors__pb2.BulkCalibrationResponse.SerializeToString,
            ),
            'EmergencyShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyShutdown,
                    request_deserializer=sensors__pb2.EmergencyShutdownRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.sensors.SensorManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.sensors.SensorManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorManagementService(object):
    """General Sensor Management Service
    """

    @staticmethod
    def RegisterSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.SensorManagementService/RegisterSensor',
            sensors__pb2.SensorRegistration.SerializeToString,
            sensors__pb2.SensorRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetZoneSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.SensorManagementService/GetZoneSensors',
            sensors__pb2.GetZoneSensorsRequest.SerializeToString,
            sensors__pb2.ZoneSensorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensorNetworkHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.SensorManagementService/GetSensorNetworkHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sensors__pb2.SensorNetworkHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkCalibrateSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.SensorManagementService/BulkCalibrateSensors',
            sensors__pb2.BulkCalibrationRequest.SerializeToString,
            sensors__pb2.BulkCalibrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.sensors.SensorManagementService/EmergencyShutdown',
            sensors__pb2.EmergencyShutdownRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
