# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vryndara.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vryndara.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evryndara.proto\x12\x08vryndara\"-\n\tAgentInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\"x\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fsource_agent_id\x18\x02 \x01(\t\x12\x17\n\x0ftarget_agent_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"$\n\x10SubscribeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"6\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"&\n\x12HealthCheckRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"I\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\xd1\x01\n\x0eRoboticCommand\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x12\n\nrobot_type\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12<\n\nparameters\x18\x04 \x03(\x0b\x32(.vryndara.RoboticCommand.ParametersEntry\x12\x16\n\x0esecurity_token\x18\x05 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"{\n\x0fSensorTelemetry\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0bsensor_type\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x32\xf6\x01\n\x0fVryndaraService\x12.\n\x08Register\x12\x13.vryndara.AgentInfo\x1a\r.vryndara.Ack\x12*\n\x07Publish\x12\x10.vryndara.Signal\x1a\r.vryndara.Ack\x12;\n\tSubscribe\x12\x1a.vryndara.SubscribeRequest\x1a\x10.vryndara.Signal0\x01\x12J\n\x0bHealthCheck\x12\x1c.vryndara.HealthCheckRequest\x1a\x1d.vryndara.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vryndara_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTICCOMMAND_PARAMETERSENTRY']._loaded_options = None
  _globals['_ROBOTICCOMMAND_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_AGENTINFO']._serialized_start=28
  _globals['_AGENTINFO']._serialized_end=73
  _globals['_SIGNAL']._serialized_start=75
  _globals['_SIGNAL']._serialized_end=195
  _globals['_SUBSCRIBEREQUEST']._serialized_start=197
  _globals['_SUBSCRIBEREQUEST']._serialized_end=233
  _globals['_ACK']._serialized_start=235
  _globals['_ACK']._serialized_end=289
  _globals['_HEALTHCHECKREQUEST']._serialized_start=291
  _globals['_HEALTHCHECKREQUEST']._serialized_end=329
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=331
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=404
  _globals['_ROBOTICCOMMAND']._serialized_start=407
  _globals['_ROBOTICCOMMAND']._serialized_end=616
  _globals['_ROBOTICCOMMAND_PARAMETERSENTRY']._serialized_start=567
  _globals['_ROBOTICCOMMAND_PARAMETERSENTRY']._serialized_end=616
  _globals['_SENSORTELEMETRY']._serialized_start=618
  _globals['_SENSORTELEMETRY']._serialized_end=741
  _globals['_VRYNDARASERVICE']._serialized_start=744
  _globals['_VRYNDARASERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)
