# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vryndara_pb2 as vryndara__pb2


class VryndaraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/vryndara.VryndaraService/Register',
                request_serializer=vryndara__pb2.AgentInfo.SerializeToString,
                response_deserializer=vryndara__pb2.Ack.FromString,
                )
        self.Publish = channel.unary_unary(
                '/vryndara.VryndaraService/Publish',
                request_serializer=vryndara__pb2.Signal.SerializeToString,
                response_deserializer=vryndara__pb2.Ack.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/vryndara.VryndaraService/Subscribe',
                request_serializer=vryndara__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=vryndara__pb2.Signal.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/vryndara.VryndaraService/HealthCheck',
                request_serializer=vryndara__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=vryndara__pb2.HealthCheckResponse.FromString,
                )


class VryndaraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VryndaraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=vryndara__pb2.AgentInfo.FromString,
                    response_serializer=vryndara__pb2.Ack.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=vryndara__pb2.Signal.FromString,
                    response_serializer=vryndara__pb2.Ack.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=vryndara__pb2.SubscribeRequest.FromString,
                    response_serializer=vryndara__pb2.Signal.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=vryndara__pb2.HealthCheckRequest.FromString,
                    response_serializer=vryndara__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vryndara.VryndaraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VryndaraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vryndara.VryndaraService/Register',
            vryndara__pb2.AgentInfo.SerializeToString,
            vryndara__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vryndara.VryndaraService/Publish',
            vryndara__pb2.Signal.SerializeToString,
            vryndara__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/vryndara.VryndaraService/Subscribe',
            vryndara__pb2.SubscribeRequest.SerializeToString,
            vryndara__pb2.Signal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vryndara.VryndaraService/HealthCheck',
            vryndara__pb2.HealthCheckRequest.SerializeToString,
            vryndara__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
